version: ‘3’
services:
  db:
    image: mysql:5.7
    volumes:
      – db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      – collabnet
  wordpress:
    depends_on:
      – db
    image: wordpress:latest
    ports:
      – “8000:80”
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      – collabnet
volumes:
  db_data:
networks:
  collabnet:
    driver: overlay